spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: true
      data-locations: classpath:demo_data.sql
security:
  jwt:
    secret: amZrZGFsO2RqZjthbHNkZiBLSjpMS0pERiBKZmpkcztsYWtzZGpmIDthc2xkaWYgamE7c2xka2YgYTtzbGRpZiA7amZka2E7bHNrZCBq
    access: 3600000
    refresh: 2592000000